version: '3.9'
services:
  auth-service:
    build: ./backend/services/auth-service
    image: platform/auth-service:latest
    environment:
      NODE_ENV: production
      PORT: 3001
    ports:
      - "3001:3000"
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  user-service:
    build: ./backend/services/user-service
    image: platform/user-service:latest
    environment:
      NODE_ENV: production
      PORT: 3002
    ports:
      - "3002:3000"
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  communication-service:
    build: ./backend/services/communication-service
    image: platform/communication-service:latest
    environment:
      NODE_ENV: production
      PORT: 3003
    ports:
      - "3003:3000"
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  notification-service:
    build: ./backend/services/notification-service
    image: platform/notification-service:latest
    environment:
      NODE_ENV: production
      PORT: 3004
    ports:
      - "3004:3000"
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  matching-service:
    build: ./backend/services/matching-service
    image: platform/matching-service:latest
    environment:
      NODE_ENV: production
      PORT: 3005
    ports:
      - "3005:3000"
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  frontend:
    build: ./frontend
    image: platform/frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - auth-service
      - user-service
      - communication-service
      - notification-service
      - matching-service

networks:
  default:
    name: platform-net
