# Railway.app deployment configuration with shared variables
# This eliminates the need to repeat environment variables across services

[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Shared environment variables for all services
[shared]
variables = [
  "DATABASE_URL",
  "JWT_SECRET", 
  "JWT_EXPIRES_IN",
  "JWT_REFRESH_EXPIRES_IN",
  "NODE_ENV",
  "CORS_ORIGIN",
  "ALLOWED_ORIGINS"
]

# All services inherit shared variables automatically
[services.auth-service]
source = "backend/services/auth-service"
healthcheckPath = "/health"
# Inherits all shared variables

[services.user-service]
source = "backend/services/user-service"  
healthcheckPath = "/health"
# Inherits all shared variables

[services.matching-service]
source = "backend/services/matching-service"
healthcheckPath = "/health" 
# Inherits all shared variables

[services.communication-service]
source = "backend/services/communication-service"
healthcheckPath = "/health"
# Inherits all shared variables

[services.notification-service]
source = "backend/services/notification-service"
healthcheckPath = "/health"
# Inherits all shared variables