# Render.com Blueprint Configuration
# This file defines all backend services for deployment

services:
  # Auth Service (Port 3001)
  - type: web
    name: staff-auth-service
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend/services/auth-service && npm install && npm run build
    startCommand: cd backend/services/auth-service && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: CORS_ORIGIN
        value: https://karnisinghji.github.io
    healthCheckPath: /health

  # User Service (Port 3002)
  - type: web
    name: staff-user-service
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend/services/user-service && npm install && npm run build
    startCommand: cd backend/services/user-service && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3002
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://karnisinghji.github.io
    healthCheckPath: /health

  # Matching Service (Port 3003)
  - type: web
    name: staff-matching-service
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend/services/matching-service && npm install && npm run build
    startCommand: cd backend/services/matching-service && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3003
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://karnisinghji.github.io
    healthCheckPath: /health

  # Communication Service (Port 3004)
  - type: web
    name: staff-communication-service
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend/services/communication-service && npm install && npm run build
    startCommand: cd backend/services/communication-service && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3004
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://karnisinghji.github.io
    healthCheckPath: /health

  # Notification Service (Port 3005)
  - type: web
    name: staff-notification-service
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend/services/notification-service && npm install && npm run build
    startCommand: cd backend/services/notification-service && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3005
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://karnisinghji.github.io
    healthCheckPath: /health
