#!/bin/bash

# Script to update remaining Railway services with Firebase CORS origins
# Run this script from the backend directory

echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║                                                                    ║"
echo "║     🚂 UPDATING REMAINING RAILWAY SERVICES                         ║"
echo "║                                                                    ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""

CORS_VALUE="https://comeondost.web.app,http://localhost:5173"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⏳ Updating matching-service-production..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run these commands manually:"
echo ""
echo "railway link"
echo "# Select: matching-service (or matching-service-production)"
echo "railway variables --set CORS_ORIGINS=\"$CORS_VALUE\""
echo "railway unlink"
echo ""
read -p "Press Enter when done with matching-service..."

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⏳ Updating communication-service-production-c165..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run these commands manually:"
echo ""
echo "railway link"
echo "# Select: communication-service"
echo "railway variables --set CORS_ORIGINS=\"$CORS_VALUE\""
echo "railway unlink"
echo ""
read -p "Press Enter when done with communication-service..."

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⏳ Updating notification-service-production-8738..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run these commands manually:"
echo ""
echo "railway link"
echo "# Select: notification-service"
echo "railway variables --set CORS_ORIGINS=\"$CORS_VALUE\""
echo "railway unlink"
echo ""
read -p "Press Enter when done with notification-service..."

echo ""
echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║                                                                    ║"
echo "║              ✅ ALL RAILWAY SERVICES UPDATED!                      ║"
echo "║                                                                    ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""
echo "Next: Update Google OAuth settings!"
echo "See: GOOGLE_OAUTH_URLS.txt"
echo ""
