#!/bin/bash
# ===========================================
# Google OAuth Client Update Reference
# ===========================================
# NOTE: Google Cloud SDK doesn't support direct OAuth client URI updates via CLI
# You MUST use the web console for this.
#
# This script is a REFERENCE showing what needs to be configured.
# ===========================================

echo "📋 Google OAuth Configuration Reference"
echo "=========================================="
echo ""
echo "🔗 Direct Link to Your OAuth Client:"
echo "https://console.cloud.google.com/apis/credentials/oauthclient/346188939499-68nadmhoo0v5d51g3l8dop77nkdm4vuu"
echo ""
echo "📧 Login with: khushabhu@gmail.com"
echo ""
echo "=========================================="
echo "✅ REQUIRED: Authorized Redirect URIs"
echo "=========================================="
echo ""
echo "Add these 4 URIs in the OAuth client:"
echo ""
echo "1. http://localhost:3001/api/auth/google/callback"
echo "   (For local development)"
echo ""
echo "2. https://auth-service.delightfulflower-04821c4b.southeastasia.azurecontainerapps.io/api/auth/google/callback"
echo "   (For Azure production backend)"
echo ""
echo "3. https://comeondost.web.app/auth/callback"
echo "   (For Firebase frontend)"
echo ""
echo "4. https://comeondost.firebaseapp.com/auth/callback"
echo "   (For Firebase frontend - alternative)"
echo ""
echo "=========================================="
echo "✅ REQUIRED: Authorized JavaScript Origins"
echo "=========================================="
echo ""
echo "Add these 4 origins:"
echo ""
echo "1. http://localhost:5173"
echo "2. https://comeondost.web.app"
echo "3. https://comeondost.firebaseapp.com"
echo "4. https://auth-service.delightfulflower-04821c4b.southeastasia.azurecontainerapps.io"
echo ""
echo "=========================================="
echo "📝 Steps:"
echo "=========================================="
echo "1. Open the link above in your browser"
echo "2. Login as khushabhu@gmail.com"
echo "3. Click 'Edit' if not already in edit mode"
echo "4. Scroll to 'Authorized redirect URIs'"
echo "5. Click '+ ADD URI' and paste each URI"
echo "6. Scroll to 'Authorized JavaScript origins'"
echo "7. Click '+ ADD URI' and paste each origin"
echo "8. Click 'SAVE' at the bottom"
echo "9. Wait 2-3 minutes for changes to propagate"
echo ""
echo "=========================================="
echo "🧪 Test After Updating:"
echo "=========================================="
echo ""
echo "Open this URL in your browser:"
echo "https://auth-service.delightfulflower-04821c4b.southeastasia.azurecontainerapps.io/api/auth/google"
echo ""
echo "Expected: Should redirect to Google sign-in page"
echo ""
echo "=========================================="
echo "✅ Done! Check GOOGLE_CONSOLE_UPDATE_GUIDE.md for more details."
