name: Deploy Backend Services to Railway

# Disabled automatic push trigger because Railway GitHub Integration will
# handle auto-deploys. Change to manual trigger to avoid duplicate deployments.
on:
  workflow_dispatch:

env:
  NODE_ENV: production
  # Updated for Firebase
  CORS_ORIGIN: https://comeondost.web.app
  ALLOWED_ORIGINS: https://comeondost.web.app,http://localhost:5173

jobs:
  # First job: Build shared library
  build-shared:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install workspace dependencies
        working-directory: backend
        run: npm install --legacy-peer-deps

      - name: Build shared library
        working-directory: backend/services/shared
        run: npm run build

      - name: Cache shared library
        uses: actions/cache@v3
        with:
          path: backend/services/shared/dist
          key: shared-${{ github.sha }}

  # Second job: Deploy services (depends on build-shared)
  deploy-services:
    needs: build-shared
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: 
          - auth-service
          - user-service
          - matching-service
          - communication-service
          - notification-service
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Restore shared library cache
        uses: actions/cache@v3
        with:
          path: backend/services/shared/dist
          key: shared-${{ github.sha }}

      - name: Install workspace dependencies
        working-directory: backend
        run: npm install --legacy-peer-deps

      - name: Build service
        working-directory: backend/services/${{ matrix.service }}
        run: npm run build

      - name: Deploy to Railway
        working-directory: backend/services/${{ matrix.service }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          echo "🚀 Deploying ${{ matrix.service }} to Railway..."
          
          # Link to Railway project
          railway link --project ${{ matrix.service }} --environment production || true
          
          # Deploy
          railway up --detach
          
          echo "✅ ${{ matrix.service }} deployed successfully!"

      - name: Verify deployment
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          echo "⏳ Waiting for deployment to complete..."
          sleep 30
          
          case "${{ matrix.service }}" in
            "auth-service")
              curl -f https://auth-service-production-d5c8.up.railway.app/health || exit 1
              ;;
            "user-service")
              curl -f https://user-service-production-f141.up.railway.app/health || exit 1
              ;;
            "matching-service")
              curl -f https://matching-service-production.up.railway.app/health || exit 1
              ;;
            "communication-service")
              curl -f https://communication-service-production-c165.up.railway.app/health || exit 1
              ;;
            "notification-service")
              curl -f https://notification-service-production-8738.up.railway.app/health || exit 1
              ;;
          esac
          
          echo "✅ Health check passed!"

  # Third job: Notify on completion
  notify:
    needs: deploy-services
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Deployment Summary
        run: |
          if [ "${{ needs.deploy-services.result }}" == "success" ]; then
            echo "✅ All services deployed successfully!"
            echo "Frontend: https://comeondost.web.app"
            echo "Backend: Railway"
          else
            echo "❌ Deployment failed. Check workflow logs."
            exit 1
          fi
